# -*- coding: utf-8 -*-
"""face_landmarks.ipynb

Automatically generated by Colaboratory.

Author: Rushit Bhadaniya

Original file is located at
    https://colab.research.google.com/drive/1R6pyypqodZLgU-Dao7Z7Z1zImgxUU1YK
"""

pip install face_recognition

import PIL.Image
import PIL.ImageDraw
import face_recognition

#load the jpeg file into a numpy array
image=face_recognition.load_image_file("rushit.jpeg")

#find all facial feature in all the faces in the image
face_landmarks_list = face_recognition.face_landmarks(image)

number_of_faces=len(face_landmarks_list)
print("I found {} face(s) in this photograph.".format(number_of_faces))

# Load the image into a Python Image Library object so that we can draw on top of it and display it
pil_image = PIL.Image.fromarray(image)

#create PIL drawing object to be draw lines later
draw= PIL.ImageDraw.Draw(pil_image)

#Loop over each face

for face_landmarks in face_landmarks_list:

  # loop over each facial feature (eye, nose , mouth ,lips,etc)
  for name,list_of_points in face_landmarks.items():
    # Print the locaton of each facial feature 
    print("The {} in this face has the following points: {}".format(name,list_of_points))
    draw.line(list_of_points,fill="red",width=5)
pil_image